
import { NetworkState, CableCategory } from '../../types';

/**
 * DXF Generator for FTTH Networks
 * Outputs ASCII DXF R12/2000 format
 */

export const generateDXF = (data: NetworkState): string => {
  let dxf = '';

  // --- SECTION: HEADER ---
  dxf += `999\nGenerated by FiberOps GIS\n`;
  dxf += `0\nSECTION\n2\nHEADER\n9\n$ACADVER\n1\nAC1009\n0\nENDSEC\n`;

  // --- SECTION: TABLES (LAYERS) ---
  dxf += `0\nSECTION\n2\nTABLES\n`;
  dxf += `0\nTABLE\n2\nLAYER\n70\n6\n`; // Table head

  // Define Layers
  const layers = [
    { name: 'FTTH_SITE', color: 1 }, // Red
    { name: 'FTTH_JOINT', color: 5 }, // Blue
    { name: 'FTTH_PCO', color: 3 },   // Green
    { name: 'FTTH_CABLE_TRANSPORT', color: 4 }, // Cyan
    { name: 'FTTH_CABLE_DISTRIBUTION', color: 2 }, // Yellow
    { name: 'FTTH_TEXT', color: 7 }   // White
  ];

  layers.forEach(l => {
    dxf += `0\nLAYER\n2\n${l.name}\n70\n0\n62\n${l.color}\n6\nCONTINUOUS\n`;
  });

  dxf += `0\nENDTAB\n0\nENDSEC\n`;

  // --- SECTION: ENTITIES ---
  dxf += `0\nSECTION\n2\nENTITIES\n`;

  // 1. SITES (Points + Text)
  data.sites.forEach(site => {
    dxf += createPoint(site.location.lng, site.location.lat, 'FTTH_SITE');
    dxf += createText(site.location.lng, site.location.lat, site.name, 'FTTH_TEXT');
  });

  // 2. JOINTS
  data.joints.forEach(joint => {
    dxf += createPoint(joint.location.lng, joint.location.lat, 'FTTH_JOINT');
    dxf += createText(joint.location.lng, joint.location.lat, joint.name, 'FTTH_TEXT', 0.00005);
  });

  // 3. PCOs
  data.pcos.forEach(pco => {
    dxf += createPoint(pco.location.lng, pco.location.lat, 'FTTH_PCO');
    dxf += createText(pco.location.lng, pco.location.lat, pco.name, 'FTTH_TEXT', 0.00005);
  });

  // 4. CABLES (Polylines)
  data.cables.forEach(cable => {
    const layer = cable.category === CableCategory.TRANSPORT ? 'FTTH_CABLE_TRANSPORT' : 'FTTH_CABLE_DISTRIBUTION';
    dxf += createPolyline(cable.path, layer);
  });

  dxf += `0\nENDSEC\n`;
  dxf += `0\nEOF\n`;

  return dxf;
};

// --- DXF ENTITY HELPERS ---

const createPoint = (x: number, y: number, layer: string) => {
  // DXF Point
  return `0\nPOINT\n8\n${layer}\n10\n${x}\n20\n${y}\n30\n0.0\n`;
};

const createText = (x: number, y: number, text: string, layer: string, height = 0.0001) => {
  // DXF Text (Simple)
  return `0\nTEXT\n8\n${layer}\n10\n${x}\n20\n${y}\n30\n0.0\n40\n${height}\n1\n${text}\n`;
};

const createPolyline = (path: {lat: number, lng: number}[], layer: string) => {
  if (path.length < 2) return '';
  let s = `0\nPOLYLINE\n8\n${layer}\n66\n1\n`;
  // Vertices
  path.forEach(p => {
    s += `0\nVERTEX\n8\n${layer}\n10\n${p.lng}\n20\n${p.lat}\n30\n0.0\n`;
  });
  s += `0\nSEQEND\n`;
  return s;
};
