
import { NetworkState, EquipmentType, CableCategory, FiberCable } from '../../types';

/**
 * KML Generator for FTTH Networks
 * Adheres to OGC KML 2.2 Standard
 */

// Helper to escape XML characters
const esc = (s: string) => (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// KML Styles (Colors in KML are AABBGGRR hex)
const STYLES = `
    <Style id="style_site">
      <IconStyle>
        <scale>1.2</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href></Icon>
        <color>ff0000ff</color>
      </IconStyle>
      <LabelStyle><scale>0.8</scale></LabelStyle>
    </Style>
    <Style id="style_joint">
      <IconStyle>
        <scale>0.8</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/shapes/placemark_square.png</href></Icon>
        <color>ff00aaff</color>
      </IconStyle>
    </Style>
    <Style id="style_pco">
      <IconStyle>
        <scale>0.7</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/shapes/polygon.png</href></Icon>
        <color>ff00ff00</color>
      </IconStyle>
    </Style>
    <Style id="style_cable_transport">
      <LineStyle>
        <color>ffaa0000</color> <!-- Dark Blue (AABBGGRR) -->
        <width>4</width>
      </LineStyle>
    </Style>
    <Style id="style_cable_distribution">
      <LineStyle>
        <color>ff00aa00</color> <!-- Green (AABBGGRR) -->
        <width>2</width>
      </LineStyle>
    </Style>
`;

export const generateKML = (data: NetworkState, scope: 'ALL' | 'VISIBLE'): string => {
  let kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>FTTH Network Export</name>
    <description>Generated by FiberOps GIS</description>
    ${STYLES}
`;

  // --- FOLDER: SITES ---
  kml += `    <Folder><name>Central Offices / Sites</name>\n`;
  data.sites.forEach(site => {
    kml += `      <Placemark>
        <name>${esc(site.name)}</name>
        <description>
          <![CDATA[
            <b>Type:</b> ${site.siteType}<br/>
            <b>Status:</b> ${site.status}<br/>
            <b>ID:</b> ${site.id}
          ]]>
        </description>
        <styleUrl>#style_site</styleUrl>
        <Point><coordinates>${site.location.lng},${site.location.lat},0</coordinates></Point>
      </Placemark>\n`;
  });
  kml += `    </Folder>\n`;

  // --- FOLDER: JOINTS ---
  kml += `    <Folder><name>Joints (Boites)</name>\n`;
  data.joints.forEach(joint => {
    kml += `      <Placemark>
        <name>${esc(joint.name)}</name>
        <description>Type: ${joint.jointType}, Capacity: ${joint.capacityFibers}F</description>
        <styleUrl>#style_joint</styleUrl>
        <Point><coordinates>${joint.location.lng},${joint.location.lat},0</coordinates></Point>
      </Placemark>\n`;
  });
  kml += `    </Folder>\n`;

  // --- FOLDER: PCOs ---
  kml += `    <Folder><name>PCOs (NAPs)</name>\n`;
  data.pcos.forEach(pco => {
    kml += `      <Placemark>
        <name>${esc(pco.name)}</name>
        <description>Ports Used: ${pco.usedPorts}/${pco.totalPorts}</description>
        <styleUrl>#style_pco</styleUrl>
        <Point><coordinates>${pco.location.lng},${pco.location.lat},0</coordinates></Point>
      </Placemark>\n`;
  });
  kml += `    </Folder>\n`;

  // --- FOLDER: TRANSPORT CABLES ---
  kml += `    <Folder><name>Transport Cables</name>\n`;
  data.cables.filter(c => c.category === CableCategory.TRANSPORT).forEach(cable => {
    kml += createCablePlacemark(cable, '#style_cable_transport');
  });
  kml += `    </Folder>\n`;

  // --- FOLDER: DISTRIBUTION CABLES ---
  kml += `    <Folder><name>Distribution Cables</name>\n`;
  data.cables.filter(c => c.category === CableCategory.DISTRIBUTION).forEach(cable => {
    kml += createCablePlacemark(cable, '#style_cable_distribution');
  });
  kml += `    </Folder>\n`;

  kml += `  </Document>
</kml>`;

  return kml;
};

const createCablePlacemark = (cable: FiberCable, styleId: string) => {
  const coordsString = cable.path.map(p => `${p.lng},${p.lat},0`).join(' ');
  return `      <Placemark>
        <name>${esc(cable.name)}</name>
        <description>
           <![CDATA[
             <b>Type:</b> ${cable.cableType} (${cable.fiberCount}F)<br/>
             <b>Length:</b> ${cable.lengthMeters}m<br/>
             <b>Endpoints:</b> ${cable.startNodeId} -> ${cable.endNodeId}
           ]]>
        </description>
        <styleUrl>${styleId}</styleUrl>
        <LineString>
          <tessellate>1</tessellate>
          <coordinates>${coordsString}</coordinates>
        </LineString>
      </Placemark>\n`;
};
